-- 코드를 입력하세요
SELECT YEAR(sales_date) AS YEAR, MONTH(sales_date) AS MONTH, GENDER, COUNT(DISTINCT a.USER_ID) AS USERS
FROM ONLINE_SALE a LEFT JOIN USER_INFO b ON a.USER_ID = b.USER_ID
GROUP BY YEAR, MONTH, GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER