-- 코드를 입력하세요
SELECT DATE_FORMAT(ONLINE_SALE.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE 
WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE <'2022-04-01'
    
UNION ALL

SELECT DATE_FORMAT(OFFLINE_SALE.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE 
WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE <'2022-04-01'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID