WITH RECURSIVE tb AS (
SELECT
    B.CATEGORY, 
    B.AUTHOR_ID,
    SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK_SALES AS S
    LEFT JOIN BOOK AS B ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY B.CATEGORY, B.AUTHOR_ID
)

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.TOTAL_SALES
FROM tb AS B
    LEFT JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
ORDER BY A.AUTHOR_ID , B.CATEGORY DESC