-- 코드를 입력하세요
SELECT 
    BOOK_ID, AUTHOR_NAME,  DATE_FORMAT(b.PUBLISHED_DATE, '%Y-%m-%d')
FROM
    BOOK b LEFT JOIN
    AUTHOR a
    ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE 
    b.CATEGORY = '경제'
ORDER BY b.PUBLISHED_DATE